[package]
name = "mytestcrate"
version = "0.3.0"
edition = "2021"
authors = ["0x5459 <0x5459@protonmail.com>"]
description = "my test crate"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
